TrainingArguments:
  num_train_epochs: 7
  warmup_steps: 500
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  learning_rate: 2e-5
  weight_decay: 0.01
  logging_steps: 10
  evaluation_strategy: epoch
  eval_steps: 500
  save_steps: 1000000 #1e6
  gradient_accumulation_steps: 16
  save_total_limit: 0
  save_strategy: 'no'