
# logs:
logs:
  logs_dir: logs
  log_file: logs/running_logs.log


# artifacts:
artifacts: 
  artifacts_dir: artifacts

  # dataset
  data:
    data_dir: artifacts/data
    raw_data_file_name: artifacts/data/data.csv
    train_torch_file_name: artifacts/data/train.pth
    valid_torch_file_name: artifacts/data/valid.pth
    test_torch_file_name: artifacts/data/test.pth
    num_of_labels_file_name: artifacts/data/labels.json
    tag2_file_name: artifacts/data/tag2id.json

  # model:
  model:
    model_dir: artifacts/model

  # tokenizer:
  tokenizer:
    tokenizer_dir: artifacts/tokenizer
  
  # performance report:
  report:
    report_dir: artifacts/report
    file_name: artifacts/report/performace_report.json


# model_info:
model_info:
  model_name: bert-base-uncased


# dataset split ratio
split_ratio:
  test_size: 0.3
  random_dtate: 42